// ECOMAX — ONE shared Supabase Auth client
const SUPABASE_URL="https://mkxkqdvtmfbxmldnvsef.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_K5orPxr9E0q9-k0dKYdt-g_0GTFvWtd";
const ECOMAX_AUTH_STORAGE="ecomax-auth";
const ECOMAX_LEGACY_STORAGE="sb-mkxkqdvtmfbxmldnvsef-auth-token";
window.ECOMAX_SUPABASE={url:SUPABASE_URL,key:SUPABASE_ANON_KEY};
(function(){try{if(!window.supabase||typeof window.supabase.createClient!=="function"){window.ECOMAX_SUPABASE_ERROR="Supabase JS SDK ვერ ჩაიტვირთა";return}if(window.ECOMAX_SUPABASE_CLIENT)return;try{const shared=localStorage.getItem(ECOMAX_AUTH_STORAGE),legacy=localStorage.getItem(ECOMAX_LEGACY_STORAGE);if(!shared&&legacy)localStorage.setItem(ECOMAX_AUTH_STORAGE,legacy)}catch(e){}const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{storageKey:ECOMAX_AUTH_STORAGE,storage:window.localStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"pkce"}});if(!client||!client.auth){window.ECOMAX_SUPABASE_ERROR="Supabase client შეიქმნა არასწორად";return}window.ECOMAX_SUPABASE_CLIENT=client;window.ECOMAX_AUTH_CLIENT=client;const originalCreateClient=window.supabase.createClient;window.supabase.createClient=function(){return window.ECOMAX_SUPABASE_CLIENT||originalCreateClient.apply(window.supabase,arguments)};async function stableSession(){for(let i=0;i<40;i++){try{const r=await client.auth.getSession(),session=r&&r.data?r.data.session:null;if(session)return session}catch(e){}await new Promise(r=>setTimeout(r,250))}return null}window.ECOMAX_AUTH_READY=stableSession().then(function(session){window.ECOMAX_CURRENT_SESSION=session||null;window.ECOMAX_CURRENT_USER=session&&session.user||null;return session||null});client.auth.onAuthStateChange(function(event,session){window.ECOMAX_CURRENT_SESSION=session||null;window.ECOMAX_CURRENT_USER=session&&session.user||null;try{if(session){const raw=localStorage.getItem(ECOMAX_AUTH_STORAGE);if(raw)localStorage.setItem(ECOMAX_LEGACY_STORAGE,raw)}else if(event==="SIGNED_OUT"){localStorage.removeItem(ECOMAX_AUTH_STORAGE);localStorage.removeItem(ECOMAX_LEGACY_STORAGE)}}catch(e){}})}catch(e){window.ECOMAX_SUPABASE_ERROR=(e&&e.message)||String(e);console.error("ECOMAX Supabase bootstrap error:",e)}})();
(function(){const path=window.location.pathname.toLowerCase();if(path.endsWith('/admin.html')||path==='admin.html'){const s=document.createElement('script');s.id='ecomaxAdminHardLockJs';s.src='js/admin-hard-lock.js?v=20260914-1';document.head.appendChild(s)}})();
(function(){function load(){if(document.getElementById("ecomaxAuthFixJs"))return;const s=document.createElement("script");s.id="ecomaxAuthFixJs";s.src="js/auth-fix.js?v=20260914-8";s.defer=true;document.head.appendChild(s)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",load);else load()})();
(function(){const path=window.location.pathname.replace(/\/+$/,'');if(!(path===''||path==='/'||path==='/index.html'))return;function css(id,href){if(document.getElementById(id))return;const x=document.createElement('link');x.id=id;x.rel='stylesheet';x.href=href;document.head.appendChild(x)}function js(id,src,cb){if(document.getElementById(id))return;const x=document.createElement('script');x.id=id;x.src=src;x.defer=true;if(cb)x.onload=cb;document.head.appendChild(x)}css('ecomaxEnhancementsCss','enhancements-v2.css?v=20260913-7');css('ecomaxStoreUiCss','store-ui.css?v=20260913-7');css('ecomaxFinalUiCss','ecomax-final-ui.css?v=20260913-1');css('ecomaxHomeV3Css','home-v3.css?v=20260916-2');css('ecomaxResponsive5DCss','css/mobile-perfect-5d.css?v=20260916-2');css('ecomaxDeviceFinalCss','css/mobile-device-final.css?v=20260916-3');css('ecomaxFinalHomeFixCss','css/final-home-fix.css?v=20260916-2');css('ecomaxResponsiveFinalCss','css/responsive-final-5d.css?v=20260916-1');css('ecomaxAbsoluteFinalCss','css/absolute-responsive-final.css?v=20260916-1');css('ecomaxGeometryNuclearCss','css/geometry-nuclear-final.css?v=20260916-2');css('ecomaxViewportLayoutLockCss','css/viewport-layout-lock.css?v=20260916-3');css('ecomaxAbsoluteViewportFinalCss','css/absolute-viewport-final-20260916.css?v=20260916-1');js('ecomaxStoreUiJs','store-ui.js?v=20260913-7');js('ecomaxFinalHomeJs','homepage-final.js?v=20260913-7',function(){if(window.ECOMAX_FINAL_INIT)window.ECOMAX_FINAL_INIT()});js('ecomaxFinalUiJs','ecomax-final-ui.js?v=20260913-1');js('ecomaxCartEmergencyFixJs','js/cart-emergency-fix.js?v=20260916-1');js('ecomaxMobileHardFixJs','js/mobile-hardfix.js?v=20260916-2');js('ecomaxFinalHomeFixJs','js/final-home-fix.js?v=20260916-2');})();
