"use strict";
let cart=[];try{cart=JSON.parse(localStorage.getItem("ecomax_cart")||"[]")}catch(e){}if(!Array.isArray(cart))cart=[];
const save=()=>localStorage.setItem("ecomax_cart",JSON.stringify(cart));
const total=()=>cart.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||0),0);
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
function note(t){document.querySelector(".ecomax-notification")?.remove();const n=document.createElement("div");n.className="ecomax-notification";n.textContent=t;Object.assign(n.style,{position:"fixed",right:"20px",bottom:"20px",zIndex:99999,padding:"14px 18px",background:"#03101c",color:"#00eaff",border:"1px solid #00eaff",borderRadius:"10px",fontWeight:"700"});document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function renderCart(){const e=document.getElementById("cartItems");if(!e)return;if(!cart.length){e.innerHTML='<div class="empty-cart"><div>🛒</div><h3>კალათა ცარიელია</h3><p>დაამატე პროდუქტი კალათაში.</p></div>';return}e.innerHTML=cart.map((i,n)=>`<div class="cart-item"><div class="cart-item-info"><strong>${esc(i.name)}</strong><span>${esc(i.volume)} × ${i.quantity}</span></div><div class="cart-item-price">${Number(i.price)*Number(i.quantity)} ₾</div><button type="button" class="remove-item" data-index="${n}">×</button></div>`).join("")}
function updateCart(){const c=cart.reduce((s,i)=>s+Number(i.quantity||0),0),ce=document.getElementById("cartCount"),te=document.getElementById("cartTotal");if(ce)ce.textContent=c;if(te)te.textContent=total()+" ₾";renderCart();save()}
function addToCart(name,price,volume){price=Number(price);if(!name||!Number.isFinite(price)||price<=0)return note("პროდუქტის დამატება ვერ მოხერხდა");const old=cart.find(i=>i.name===name&&i.volume===volume);if(old)old.quantity=Number(old.quantity||0)+1;else cart.push({name,price,volume:volume||"",quantity:1});updateCart();note(name+" დაემატა კალათაში")}
function removeFromCart(i){if(i>=0&&i<cart.length){cart.splice(i,1);updateCart()}}
function openCart(){const e=document.getElementById("cartOverlay");if(e){e.classList.add("active");document.body.style.overflow="hidden";renderCart()}}
function closeCart(){const e=document.getElementById("cartOverlay");if(e){e.classList.remove("active");document.body.style.overflow=""}}
function volumeUpdate(card){const s=card.querySelector(".volume-select"),p=card.querySelector(".selected-price"),v=card.querySelector(".selected-volume"),b=card.querySelector(".add-cart");if(!s||!p||!v||!b)return;const vol=Number(s.value)||.5,price=vol*Number(card.dataset.unitPrice||10),label=vol===.5?"500 მლ":vol+" ლიტრი";p.textContent=price+" ₾";v.textContent=label;b.dataset.price=price;b.dataset.volume=label}
function checkout(){if(!cart.length)return note("კალათა ცარიელია");save();location.href="checkout.html"}
window.addToCart=addToCart;window.openCart=openCart;window.closeCart=closeCart;window.removeFromCart=removeFromCart;window.goToCheckout=checkout;window.renderCart=renderCart;
function init(){document.querySelectorAll(".product-card").forEach(c=>{volumeUpdate(c);c.querySelector(".volume-select")?.addEventListener("change",()=>volumeUpdate(c))});document.addEventListener("click",e=>{const a=e.target.closest?.(".add-cart");if(a){e.preventDefault();addToCart(a.dataset.name,a.dataset.price,a.dataset.volume);return}const cb=e.target.closest?.("#cartButton");if(cb){e.preventDefault();openCart();return}const x=e.target.closest?.("#checkoutButton");if(x){e.preventDefault();checkout();return}const r=e.target.closest?.(".remove-item");if(r){e.preventDefault();removeFromCart(Number(r.dataset.index));return}if(e.target.closest?.("#closeCart")){e.preventDefault();closeCart();return}const o=document.getElementById("cartOverlay");if(o&&e.target===o)closeCart()});const m=document.getElementById("menuButton"),n=document.getElementById("mobileNav");if(m&&n)m.addEventListener("click",()=>n.classList.toggle("active"));if(n)n.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>n.classList.remove("active")));updateCart()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
