(function(){
'use strict';
const CAT={ENGINE:['ძრავი','⚙️'],LEATHER:['ტყავი','◈'],TEXTILE:['ნაჭერი','▦'],WHEEL:['დისკები','◉'],RADIATOR:['რადიატორი','▥'],RUST:['ჟანგი','⚡'],TIRE:['საბურავი','◌'],DASH:['პლასტმასი','◆'],FOAM:['ქაფი','☁'],PERFUME:['სურნელი','✦'],OTHER:['სხვა','✧']};
let active='ALL',modalCard=null,modalVolume=.5,modalQty=1;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const cards=()=>$$('#productsGrid .product-card');
const tag=c=>(($('.product-tag',c)?.textContent||'OTHER').trim().toUpperCase());
const cat=t=>CAT[t]||CAT.OTHER;
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const volumeLabel=v=>v===.5?'500 მლ':v+' ლიტრი';
function data(c){const s=$('.volume-select',c);const opts=s?[...s.options].map(o=>({v:num(o.value),t:o.textContent.trim()})):[{v:.5,t:'500 მლ — 5 ₾'},{v:1,t:'1 ლიტრი — 10 ₾'}];return{name:$('h3',c)?.textContent.trim()||'ECOMAX პროდუქტი',desc:$('p',c)?.textContent.trim()||'',details:$$('.product-details div',c).map(x=>x.textContent.trim()).join(' '),opts,unit:num(c.dataset.unitPrice)||10,tag:tag(c),code:$('.product-number',c)?.textContent.trim()||''};}
function refresh(c){const s=$('.volume-select',c);if(!s)return;const v=num(s.value)||.5,p=v*(num(c.dataset.unitPrice)||10),l=volumeLabel(v);if($('.selected-price',c))$('.selected-price',c).textContent=p+' ₾';if($('.selected-volume',c))$('.selected-volume',c).textContent=l;const b=$('.add-cart',c);if(b){b.dataset.price=p;b.dataset.volume=l;}}
function addMany(name,price,vol,q){if(typeof window.addToCart!=='function')return;for(let i=0;i<q;i++)window.addToCart(name,price,vol);}
function cardControls(c){refresh(c);const s=$('.volume-select',c);if(s&&!s.dataset.storeBound){s.dataset.storeBound='1';s.addEventListener('change',()=>refresh(c));}
let old=$('.add-cart',c);if(old&&!old.dataset.store){const b=old.cloneNode(true);b.dataset.store='1';old.replaceWith(b);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();refresh(c);const d=data(c);addMany(d.name,num(b.dataset.price)||d.unit*.5,b.dataset.volume||'500 მლ',num($('.store-qty-value',c)?.textContent)||1);});}
if(!$('.store-qty',c)){const q=document.createElement('div');q.className='store-qty';q.innerHTML='<span class="store-qty-label">რაოდენობა</span><div class="store-qty-controls"><button type="button" data-q="-">−</button><span class="store-qty-value">1</span><button type="button" data-q="+">+</button></div>';const b=$('.add-cart',c);if(b)b.parentNode.insertBefore(q,b);q.addEventListener('click',e=>{const b=e.target.closest('[data-q]');if(!b)return;const n=$('.store-qty-value',q);let v=num(n.textContent)||1;v=b.dataset.q==='+'?Math.min(99,v+1):Math.max(1,v-1);n.textContent=v;});}
if(!$('.store-card-actions',c)){const b=$('.add-cart',c);if(b){const w=document.createElement('div');w.className='store-card-actions';b.parentNode.insertBefore(w,b);w.appendChild(b);const d=document.createElement('button');d.type='button';d.className='store-detail-btn';d.textContent='დეტალურად';w.appendChild(d);d.addEventListener('click',()=>openModal(c));}}
}
function chrome(grid){if($('.store-category-strip'))return;const sec=grid.closest('.products-section');if(!sec)return;const tags=[...new Set(cards().map(tag))];const strip=document.createElement('div');strip.className='store-category-strip';[['ALL','ყველა','▦'],...tags.map(t=>[t,cat(t)[0],cat(t)[1]])].forEach(x=>{const b=document.createElement('button');b.type='button';b.className='store-category-chip'+(x[0]==='ALL'?' active':'');b.dataset.cat=x[0];b.innerHTML='<span class="cat-icon">'+x[2]+'</span>'+x[1];b.onclick=()=>setCat(x[0]);strip.appendChild(b);});sec.querySelector('.section-heading')?.after(strip);
const bar=document.createElement('div');bar.className='store-toolbar';bar.innerHTML='<div><b>ECOMAX SHOP</b><span id="storeResultCount"></span></div><select id="storeSort"><option value="default">რეკომენდებული</option><option value="asc">ფასი: დაბლიდან</option><option value="desc">ფასი: მაღლიდან</option><option value="name">სახელით</option></select>';strip.after(bar);$('#storeSort').onchange=sort;
const lay=document.createElement('div');lay.className='store-layout';const side=document.createElement('aside');side.className='store-sidebar';side.innerHTML='<div class="store-sidebar-head">კატეგორიები</div><div class="store-sidebar-list"></div><div class="store-sidebar-foot"><b>მოცულობა</b><span>500 მლ — 20 ლიტრი</span></div>';const list=$('.store-sidebar-list',side);const counts={ALL:cards().length};tags.forEach(t=>counts[t]=(counts[t]||0)+cards().filter(c=>tag(c)===t).length);[['ALL','ყველა პროდუქტი','▦'],...tags.map(t=>[t,cat(t)[0],cat(t)[1]])].forEach(x=>{const b=document.createElement('button');b.type='button';b.className='store-sidebar-item'+(x[0]==='ALL'?' active':'');b.dataset.cat=x[0];b.innerHTML='<span>'+x[2]+' '+x[1]+'</span><b>'+counts[x[0]]+'</b>';b.onclick=()=>setCat(x[0]);list.appendChild(b);});grid.parentNode.insertBefore(lay,grid);lay.append(side);const wrap=document.createElement('div');wrap.className='store-grid-wrap';lay.append(wrap);wrap.append(grid);document.body.classList.add('store-ui-ready');}
function setCat(k){active=k;$$('.store-category-chip').forEach(b=>b.classList.toggle('active',b.dataset.cat===k));$$('.store-sidebar-item').forEach(b=>b.classList.toggle('active',b.dataset.cat===k));cards().forEach(c=>c.classList.toggle('store-hidden',k!=='ALL'&&tag(c)!==k));count();}
function count(){const n=cards().filter(c=>!c.classList.contains('store-hidden')).length;const e=$('#storeResultCount');if(e)e.textContent=' • '+n+' პროდუქტი';}
function sort(){const g=$('#productsGrid'),m=$('#storeSort')?.value;if(!g)return;const a=cards();a.sort((x,y)=>m==='asc'?data(x).unit-data(y).unit:m==='desc'?data(y).unit-data(x).unit:m==='name'?data(x).name.localeCompare(data(y).name,'ka'):0);a.forEach(c=>g.appendChild(c));setCat(active);}
function modal(){if($('#ecomaxStoreModal'))return;const m=document.createElement('div');m.id='ecomaxStoreModal';m.className='store-modal-backdrop';m.innerHTML='<div class="store-modal"><button class="store-modal-close">×</button><div class="store-modal-inner"><div class="store-modal-visual"><div class="store-modal-orbit"></div><div class="store-modal-bottle"><strong id="storeBottleText">ECOMAX</strong><span>PROFESSIONAL AUTO CARE</span></div></div><div class="store-modal-content"><small id="storeModalTag">ENGINE</small><h3 id="storeModalName">პროდუქტი</h3><p id="storeModalSubtitle"></p><div class="store-rating">★★★★★</div><div class="store-modal-price"><strong id="storeModalPrice">5 ₾</strong><span id="storeModalVolume">500 მლ</span></div><b class="store-volume-title">მოცულობის არჩევა</b><div id="storeVolumeOptions" class="store-volume-options"></div><b class="store-volume-title">რაოდენობა</b><div class="store-modal-qty"><button id="storeQtyMinus">−</button><span id="storeModalQty">1</span><button id="storeQtyPlus">+</button></div><button id="storeModalAdd" class="store-modal-add">🛒 + კალათაში</button><div class="store-modal-info"><div><h4>აღწერა</h4><p id="storeModalDesc"></p></div><div><h4>მოხმარება / გაზავება</h4><p id="storeModalDetails"></p></div></div></div></div></div>';document.body.appendChild(m);$('.store-modal-close',m).onclick=closeModal;m.onclick=e=>{if(e.target===m)closeModal();};$('#storeQtyMinus').onclick=()=>{modalQty=Math.max(1,modalQty-1);renderQty();};$('#storeQtyPlus').onclick=()=>{modalQty=Math.min(99,modalQty+1);renderQty();};$('#storeModalAdd').onclick=()=>{if(!modalCard)return;const d=data(modalCard);addMany(d.name,modalVolume*d.unit,volumeLabel(modalVolume),modalQty);closeModal();};}
function renderQty(){if($('#storeModalQty'))$('#storeModalQty').textContent=modalQty;}
function openModal(c){modal();modalCard=c;modalQty=1;const d=data(c);modalVolume=num($('.volume-select',c)?.value)||d.opts[0]?.v||.5;$('#storeModalTag').textContent=d.tag;$('#storeModalName').textContent=d.name;$('#storeModalSubtitle').textContent='ECOMAX '+cat(d.tag)[0]+' • '+(d.code||'PRO');$('#storeModalDesc').textContent=d.desc;$('#storeModalDetails').textContent=d.details||'გამოიყენე ეტიკეტზე მითითებული წესის მიხედვით.';$('#storeBottleText').textContent=d.name.toUpperCase();const box=$('#storeVolumeOptions');box.innerHTML='';d.opts.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='store-volume-option'+(o.v===modalVolume?' active':'');b.textContent=o.t;b.onclick=()=>{modalVolume=o.v;renderModal();};box.appendChild(b);});renderQty();renderModal();$('#ecomaxStoreModal').classList.add('active');document.body.style.overflow='hidden';}
function renderModal(){if(!modalCard)return;const d=data(modalCard);$('#storeModalPrice').textContent=modalVolume*d.unit+' ₾';$('#storeModalVolume').textContent=volumeLabel(modalVolume);$$('.store-volume-option').forEach(b=>b.classList.toggle('active',b.textContent.includes(volumeLabel(modalVolume))));}
function closeModal(){const m=$('#ecomaxStoreModal');if(m)m.classList.remove('active');document.body.style.overflow='';modalCard=null;}
function init(){const g=$('#productsGrid');if(!g||!cards().length)return;chrome(g);cards().forEach(cardControls);count();modal();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
